name: Build and Push Images

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_CR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/frontend:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

  build-backend:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/backend:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
